#!/usr/bin/env zsh

stow_dotfile() {
  if [ -d "./$1" ]; then
    stow -D $1
    stow -S $1
    echo "info: '$1' installed."
    return 0
  else
    echo "error: invalid package"
    return 1
  fi
}

if [ -n "$1" ]; then
  stow_dotfile $1
  return $?
fi

STOW_FOLDERS="$(find . -maxdepth 1 -type d ! -name '.*')"

for folder in $(echo $STOW_FOLDERS | sed "s/\.\// /g")
do
  stow_dotfile $folder
done
