#!/usr/bin/env zsh

pushd $HOME/.dotfiles_v2

STOW_FOLDERS="$(find . -maxdepth 1 -type d ! -name '.*')"

for folder in $(echo $STOW_FOLDERS | sed "s/\.\// /g")
do
  echo "stow $folder"
  stow -D $folder
  stow -S $folder
done

popd
