icons_format = "{icon}"

[theme]
theme = "ctp-mocha"
[theme.overrides]
separator = ""
end_separator = ""

[icons]
icons = "material-nf"

[[block]]
block = "focused_window"
format = "[$title.str(max_w:64)] |"

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90
format = "[$icon cpu$utilization]"

[[block]]
block = "memory"
format = "[$icon mem $mem_used.eng(prefix:Mi) $icon_swap swap$swap_used.eng(prefix:Mi)]"

[[block]] 
block = "amd_gpu"
format = "[$icon  gpu$utilization $vram_used]"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "[$icon root $available.eng(w:2) "

[[block]]
block = "disk_space"
path = "/mnt/data"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon data$available.eng(w:2) "

[[block]]
block = "disk_space"
path = "/mnt/games"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon games $available.eng(w:2)]"

[[block]]
block = "sound"
driver = "auto"
format = "[$icon {$volume.eng(w:2)|}]"

[[block]]
block = "time"
interval = 5
format = "[$timestamp.datetime(f:'%a %d/%m %R')]"
