icons_format = "{icon}"

[theme]
theme = "nord-dark"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"
separator = ""
end_separator = ""

[icons]
icons = "material-nf"

[[block]]
block = "focused_window"

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]] 
block = "amd_gpu"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "disk_space"
path = "/mnt/data"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon data: $available.eng(w:2) "

[[block]]
block = "disk_space"
path = "/mnt/games"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon games: $available.eng(w:2) "

[[block]]
block = "sound"
driver = "auto"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
