#!/usr/bin/env zsh

export EDITOR=nvim
export BROWSER=firefox

export ZSH="$HOME/.local/share/oh-my-zsh"

if [ ! -d "$ZSH" ]; then 
  CHSH=no RUNZSH=no KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

ZSH_THEME="robbyrussell"
DISABLE_UPDATE_PROMPT="true"
ENABLE_CORRECTION="false"
COMPLETION_WAITING_DOTS="true"
plugins=(git nvm docker docker-compose)
source "$ZSH/oh-my-zsh.sh"

[[ -n "$SSH_CONNECTION" ]] && PROMPT="%{$fg_bold[red]%}[%m] $PROMPT"

alias vi=nvim
alias vim=nvim

bindkey -v
bindkey -s ^P "tmux-sessionizer\n"
bindkey -s ^O "tmux-sessionizer $HOME\n"

export MISE_NODE_DEFAULT_PACKAGES_FILE="$HOME/.config/mise/default-npm-packages"
export MISE_RUBY_DEFAULT_PACKAGES_FILE="$HOME/.config/mise/default-gems"
export MISE_PYTHON_DEFAULT_PACKAGES_FILE="$HOME/.config/mise/default-python-packages"

eval "$(mise activate zsh)"

export PATH="$HOME/.local/bin:$PATH"
