#!/usr/bin/env zsh

# Keep dotfiles up to date, checks once every 24h
DOT_DIRS=(
  "$HOME/Code/gstnlss/dotfiles"
  "$HOME/Code/gstnlss/ume.nvim"
)
for repo in "${DOT_DIRS[@]}"; do
  if [ -d "$repo/.git" ]; then
    flag_file="$repo/.last_pulled_time"

    if [ ! -f "$flag_file" ]; then
      (cd "$repo" && git pull)
      date +%s > "$flag_file"
    else
      last_pull=$(cat "$flag_file")
      now=$(date +%s)
      elapsed=$(( now - last_pull ))

      if (( elapsed > 86400 )); then
        (cd "$repo" && git pull)
        date +%s > "$flag_file"
      fi
    fi
  fi
done

export LANG="en_US.UTF-8"
export EDITOR="nvim"
export BROWSER="firefox"

export ZSH="$HOME/.local/share/oh-my-zsh"

if [ ! -d "$ZSH" ]; then 
  CHSH=no RUNZSH=no KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

ZSH_THEME="robbyrussell"
DISABLE_UPDATE_PROMPT="true"
ENABLE_CORRECTION="false"
COMPLETION_WAITING_DOTS="true"
plugins=(git nvm docker docker-compose)
source "$ZSH/oh-my-zsh.sh"

[[ -n "$SSH_CONNECTION" ]] && PROMPT="%{$fg_bold[red]%}[%m] $PROMPT"

alias v=nvim
alias vi=nvim
alias vim=nvim

bindkey -v
bindkey -s ^P "tmux-sessionizer\n"
bindkey -s ^O "tmux-sessionizer $HOME\n"

export PATH="$HOME/.local/bin:$HOME/.luarocks/bin:$PATH"
OS="$(uname)"
if [[ "$OS" == "Linux" ]]; then
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
elif [[ "$OS" == "Darwin" ]]; then
  export PATH="$HOME/.local/bin:/opt/homebrew/bin:$PATH"
else
  echo "System without homebrew support"
fi

export MISE_NODE_DEFAULT_PACKAGES_FILE="$HOME/.config/mise/default-npm-packages"
export MISE_RUBY_DEFAULT_PACKAGES_FILE="$HOME/.config/mise/default-gems"
export MISE_PYTHON_DEFAULT_PACKAGES_FILE="$HOME/.config/mise/default-python-packages"
eval "$(mise activate zsh)"
